import { LOC_METRO_COLLASSATA } from "./LOC_METRO_COLLASSATA.js";
import { LOC_DATA_CENTER } from "./LOC_DATA_CENTER.js";
import { LOC_QUARTIERE_SOMMERSO } from "./LOC_QUARTIERE_SOMMERSO.js";
import { LOC_IMPIANTO_DEPURAZ } from "./LOC_IMPIANTO_DEPURAZ.js";
import { LOC_MAGAZZINI_LOG } from "./LOC_MAGAZZINI_LOG.js";
import { LOC_OSPEDALE_SUP } from "./LOC_OSPEDALE_SUP.js";
import { LOC_CANTIERE_TUNNEL } from "./LOC_CANTIERE_TUNNEL.js";
import { LOC_CENTRO_COMM } from "./LOC_CENTRO_COMM.js";
import { LOC_DISCARICA_TEC } from "./LOC_DISCARICA_TEC.js";
import { LOC_ASCENSORE_SUP } from "./LOC_ASCENSORE_SUP.js";

export const LOCATIONS = {
  LOC_METRO_COLLASSATA,
  LOC_DATA_CENTER,
  LOC_QUARTIERE_SOMMERSO,
  LOC_IMPIANTO_DEPURAZ,
  LOC_MAGAZZINI_LOG,
  LOC_OSPEDALE_SUP,
  LOC_CANTIERE_TUNNEL,
  LOC_CENTRO_COMM,
  LOC_DISCARICA_TEC,
  LOC_ASCENSORE_SUP
};
